# Generated by Django 6.0.6 on 2026-07-13 16:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(blank=True, max_length=100, null=True)),
                ('action_type', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سجل الإجراءات',
                'verbose_name_plural': 'سجلات الإجراءات',
                'db_table': 'action_log',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'الفرع / المخزن',
                'verbose_name_plural': 'الفروع / المخازن',
                'db_table': 'branch',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'المورد',
                'verbose_name_plural': 'الموردون',
                'db_table': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('initial_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('initial_purchase_price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('initial_commission_amount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('initial_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('initial_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2025)])),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='api.branch')),
            ],
            options={
                'verbose_name': 'صنف البضاعة',
                'verbose_name_plural': 'أصناف البضاعة',
                'db_table': 'inventory_item',
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('invoice_type', models.CharField(choices=[('PURCHASE', 'فاتورة شراء'), ('RETURN', 'فاتورة مرتجع')], max_length=20)),
                ('invoice_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('invoice_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2025)])),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', to='api.branch')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', to='api.supplier')),
            ],
            options={
                'verbose_name': 'فاتورة الشراء',
                'verbose_name_plural': 'فواتير الشراء',
                'db_table': 'purchase_invoice',
            },
        ),
        migrations.CreateModel(
            name='Salesperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('is_device_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salespeople', to='api.branch')),
            ],
            options={
                'verbose_name': 'المندوب',
                'verbose_name_plural': 'المناديب',
                'db_table': 'salesperson',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('receipt_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('receipt_hash', models.CharField(max_length=255, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=150, null=True)),
                ('total_amount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('down_payment', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('installment_system', models.CharField(blank=True, max_length=255, null=True)),
                ('sale_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2025)])),
                ('sale_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('is_cash_sale', models.BooleanField(default=False)),
                ('products_text', models.TextField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at_local', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='api.branch')),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='api.salesperson')),
            ],
            options={
                'verbose_name': 'الفاتورة',
                'verbose_name_plural': 'الفواتير',
                'db_table': 'receipt',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'الشركة',
                'verbose_name_plural': 'الشركات',
                'db_table': 'tenant',
                'indexes': [models.Index(fields=['id'], name='idx_tenant_active')],
            },
        ),
        migrations.AddField(
            model_name='supplier',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='api.tenant'),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salespeople', to='api.tenant'),
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='api.inventoryitem')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='api.receipt')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='api.tenant')),
            ],
            options={
                'verbose_name': 'صنف مباع',
                'verbose_name_plural': 'الأصناف المباعة',
                'db_table': 'sale_item',
            },
        ),
        migrations.AddField(
            model_name='receipt',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='api.tenant'),
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('purchase_price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoice_items', to='api.inventoryitem')),
                ('purchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.purchaseinvoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoice_items', to='api.tenant')),
            ],
            options={
                'verbose_name': 'صنف فاتورة شراء',
                'verbose_name_plural': 'أصناف فواتير الشراء',
                'db_table': 'purchase_invoice_item',
            },
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', to='api.tenant'),
        ),
        migrations.CreateModel(
            name='PendingExternalReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=100)),
                ('source', models.CharField(choices=[('CLOUD', 'سحابة'), ('USB', 'USB'), ('FILE', 'ملف')], max_length=20)),
                ('payload', models.JSONField()),
                ('is_processed', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_external_receipts', to='api.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_external_receipts', to='api.tenant')),
            ],
            options={
                'verbose_name': 'وصل خارجي مؤقت',
                'verbose_name_plural': 'الوصلات الخارجية المؤقتة',
                'db_table': 'pending_external_receipt',
            },
        ),
        migrations.CreateModel(
            name='LicenseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=100)),
                ('operation_type', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('added_balance', models.IntegerField(default=0)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='license_histories', to='api.tenant')),
            ],
            options={
                'verbose_name': 'سجل ترخيص',
                'verbose_name_plural': 'سجلات التراخيص',
                'db_table': 'license_history',
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='api.tenant'),
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('DEFICIT', 'عجز (-)'), ('SURPLUS', 'زيادة (+)')], max_length=20)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('adjustment_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('adjustment_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2025)])),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_adjustments', to='api.inventoryitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_adjustments', to='api.tenant')),
            ],
            options={
                'verbose_name': 'تسوية المخزون',
                'verbose_name_plural': 'تسويات المخزون',
                'db_table': 'inventory_adjustment',
            },
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_payments', to='api.receipt')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_payments', to='api.tenant')),
            ],
            options={
                'verbose_name': 'قسط',
                'verbose_name_plural': 'الأقساط',
                'db_table': 'installment_payment',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.CharField(max_length=255)),
                ('expense_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2025)])),
                ('expense_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at_local', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.tenant')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصروفات',
                'db_table': 'expense',
            },
        ),
        migrations.CreateModel(
            name='CompanySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('footer_text', models.CharField(blank=True, max_length=250, null=True)),
                ('is_cloud_viewer', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='company_setting', to='api.tenant')),
            ],
            options={
                'verbose_name': 'إعدادات الشركة',
                'verbose_name_plural': 'إعدادات الشركات',
                'db_table': 'company_setting',
            },
        ),
        migrations.CreateModel(
            name='CommissionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_amount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('activation_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('activation_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2025)])),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_history', to='api.inventoryitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_histories', to='api.tenant')),
            ],
            options={
                'verbose_name': 'سجل العمولة',
                'verbose_name_plural': 'سجل العمولات',
                'db_table': 'commission_history',
            },
        ),
        migrations.CreateModel(
            name='CloudUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('ADMIN', 'مدير النظام'), ('CASHIER', 'أمين الخزنة'), ('VIEWER', 'مستخدم السحابة'), ('BRANCH_MANAGER', 'مدير الفرع')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='cloud_users', to='api.tenant')),
            ],
            options={
                'verbose_name': 'مستخدم السحابة',
                'verbose_name_plural': 'مستخدمو السحابة',
                'db_table': 'cloud_user',
            },
        ),
        migrations.CreateModel(
            name='ClientLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)])),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('invoices_balance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('machine_id', models.CharField(max_length=255)),
                ('company_code', models.CharField(max_length=10)),
                ('license_code_hash', models.CharField(max_length=64)),
                ('is_online_active', models.BooleanField(default=False)),
                ('online_start_date', models.DateField(blank=True, null=True)),
                ('online_expiry_date', models.DateField(blank=True, null=True)),
                ('last_checkin', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='client_licenses', to='api.tenant')),
            ],
            options={
                'verbose_name': 'ترخيص عميل',
                'verbose_name_plural': 'تراخيص العملاء',
                'db_table': 'client_license',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='api.tenant'),
        ),
        migrations.CreateModel(
            name='UsedLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64, unique=True)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='used_licenses', to='api.tenant')),
            ],
            options={
                'verbose_name': 'كود مستخدم',
                'verbose_name_plural': 'الأكواد المستخدمة',
                'db_table': 'used_license',
            },
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['tenant'], name='idx_supplier_tenant'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('tenant', 'name'), name='uq_tenant_supplier_name'),
        ),
        migrations.AddIndex(
            model_name='salesperson',
            index=models.Index(fields=['tenant'], name='idx_salesperson_tenant'),
        ),
        migrations.AddConstraint(
            model_name='salesperson',
            constraint=models.UniqueConstraint(fields=('tenant', 'local_id'), name='uq_tenant_salesperson_local_id'),
        ),
        migrations.AddConstraint(
            model_name='salesperson',
            constraint=models.CheckConstraint(condition=models.Q(('local_id__gte', 0)), name='chk_salesperson_local_id_gte_0'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['receipt'], name='idx_sale_item_receipt'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='chk_sale_item_quantity_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='chk_sale_item_unit_price_gte_0'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['tenant', 'branch'], name='idx_receipt_tenant_branch'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['receipt_hash'], name='idx_receipt_hash'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('local_id__gte', 0)), name='chk_receipt_local_id_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('receipt_number__gte', 0)), name='chk_receipt_number_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='chk_receipt_total_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('down_payment__gte', 0)), name='chk_receipt_down_payment_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('sale_year__gte', 2025)), name='chk_receipt_sale_year_gte_2025'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('sale_month__gte', 1), ('sale_month__lte', 12)), name='chk_receipt_sale_month_range'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoiceitem',
            index=models.Index(fields=['purchase_invoice'], name='idx_pur_inv_item_inv'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='chk_pi_item_quantity_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_price__gte', 0)), name='chk_pi_item_purchase_price_gte_0'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['tenant', 'branch'], name='idx_pur_inv_ten_branch'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoice',
            constraint=models.UniqueConstraint(fields=('tenant', 'branch', 'invoice_number', 'invoice_type'), name='uq_tenant_branch_invoice_num_type'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('invoice_number__gte', 0)), name='chk_purchase_invoice_number_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('invoice_type__in', ['PURCHASE', 'RETURN'])), name='chk_purchase_invoice_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('invoice_month__gte', 1), ('invoice_month__lte', 12)), name='chk_purchase_invoice_month_range'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('invoice_year__gte', 2025)), name='chk_purchase_invoice_year_gte_2025'),
        ),
        migrations.AddConstraint(
            model_name='pendingexternalreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['CLOUD', 'USB', 'FILE'])), name='chk_pending_receipt_source_valid'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['tenant', 'branch'], name='idx_inv_item_ten_branch'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('tenant', 'local_id'), name='uq_tenant_item_local_id'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('local_id__gte', 0)), name='chk_inventory_item_local_id_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('initial_quantity__gte', 0)), name='chk_inventory_item_initial_qty_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('initial_purchase_price__gte', 0)), name='chk_inventory_item_purchase_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('initial_commission_amount__gte', 0)), name='chk_inventory_item_commission_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('initial_month__gte', 1), ('initial_month__lte', 12)), name='chk_inventory_item_month_range'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('initial_year__gte', 2025)), name='chk_inventory_item_year_gte_2025'),
        ),
        migrations.AddIndex(
            model_name='inventoryadjustment',
            index=models.Index(fields=['inventory_item'], name='idx_inventory_adjustment_item'),
        ),
        migrations.AddConstraint(
            model_name='inventoryadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('adjustment_type__in', ['DEFICIT', 'SURPLUS'])), name='chk_adjustment_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='inventoryadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='chk_adjustment_quantity_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='inventoryadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('adjustment_month__gte', 1), ('adjustment_month__lte', 12)), name='chk_adjustment_month_range'),
        ),
        migrations.AddConstraint(
            model_name='inventoryadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('adjustment_year__gte', 2025)), name='chk_adjustment_year_gte_2025'),
        ),
        migrations.AddIndex(
            model_name='installmentpayment',
            index=models.Index(fields=['receipt'], name='idx_inst_pay_receipt'),
        ),
        migrations.AddConstraint(
            model_name='installmentpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='chk_installment_amount_gte_0'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['tenant', 'branch'], name='idx_expense_tenant_branch'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='chk_expense_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('expense_year__gte', 2025)), name='chk_expense_year_gte_2025'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('expense_month__gte', 1), ('expense_month__lte', 12)), name='chk_expense_month_range'),
        ),
        migrations.AddConstraint(
            model_name='companysetting',
            constraint=models.UniqueConstraint(fields=('tenant',), name='uq_tenant_company_setting'),
        ),
        migrations.AddIndex(
            model_name='commissionhistory',
            index=models.Index(fields=['inventory_item'], name='idx_commission_history_item'),
        ),
        migrations.AddConstraint(
            model_name='commissionhistory',
            constraint=models.CheckConstraint(condition=models.Q(('commission_amount__gte', 0)), name='chk_commission_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='commissionhistory',
            constraint=models.CheckConstraint(condition=models.Q(('activation_month__gte', 1), ('activation_month__lte', 12)), name='chk_commission_month_range'),
        ),
        migrations.AddConstraint(
            model_name='commissionhistory',
            constraint=models.CheckConstraint(condition=models.Q(('activation_year__gte', 2025)), name='chk_commission_year_gte_2025'),
        ),
        migrations.AddIndex(
            model_name='clouduser',
            index=models.Index(fields=['tenant'], name='idx_cloud_user_tenant'),
        ),
        migrations.AddConstraint(
            model_name='clouduser',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('tenant', 'username'), name='uq_tenant_username'),
        ),
        migrations.AddConstraint(
            model_name='clouduser',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['ADMIN', 'CASHIER', 'VIEWER', 'BRANCH_MANAGER'])), name='chk_cloud_user_role'),
        ),
        migrations.AddIndex(
            model_name='clientlicense',
            index=models.Index(fields=['tenant'], name='idx_client_license_tenant'),
        ),
        migrations.AddIndex(
            model_name='clientlicense',
            index=models.Index(fields=['license_code_hash'], name='idx_client_license_hash'),
        ),
        migrations.AddConstraint(
            model_name='clientlicense',
            constraint=models.CheckConstraint(condition=models.Q(('product_id__gte', 1), ('product_id__lte', 16)), name='chk_client_license_product_id_range'),
        ),
        migrations.AddConstraint(
            model_name='clientlicense',
            constraint=models.CheckConstraint(condition=models.Q(('invoices_balance__gte', 0)), name='chk_client_license_balance_gte_0'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['tenant'], name='idx_branch_tenant'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('tenant', 'local_id'), name='uq_tenant_branch_local_id'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('tenant', 'name'), name='uq_tenant_branch_name'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.CheckConstraint(condition=models.Q(('local_id__gte', 0)), name='chk_branch_local_id_gte_0'),
        ),
        migrations.AddIndex(
            model_name='usedlicense',
            index=models.Index(fields=['code_hash'], name='idx_used_license_hash'),
        ),
    ]
