# Generated by Django 6.0.6 on 2026-06-27 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(blank=True, max_length=100, null=True)),
                ('action_type', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_synced', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClientLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('invoices_balance', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('machine_id', models.CharField(blank=True, max_length=255, null=True)),
                ('license_code_hash', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company_code', models.CharField(blank=True, max_length=4, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('footer_text', models.CharField(default='تطبق الشروط والأحكام', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('operation_type', models.CharField(max_length=50)),
                ('added_balance', models.IntegerField(default=0)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PendingExternalReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(blank=True, default='', max_length=100)),
                ('payload', models.JSONField()),
                ('is_processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.PositiveIntegerField(unique=True)),
                ('invoice_type', models.CharField(choices=[('PURCHASE', 'فاتورة شراء'), ('RETURN', 'فاتورة مرتجع')], default='PURCHASE', max_length=20)),
                ('invoice_month', models.PositiveIntegerField()),
                ('invoice_year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsedLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64, unique=True)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('initial_quantity', models.PositiveIntegerField(default=0)),
                ('initial_purchase_price', models.PositiveIntegerField(default=0)),
                ('initial_commission_amount', models.PositiveIntegerField(default=0)),
                ('initial_month', models.PositiveIntegerField(default=1)),
                ('initial_year', models.PositiveIntegerField(default=2026)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.branch')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('DEFICIT', 'عجز (-)'), ('SURPLUS', 'زيادة (+)')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_amount', models.PositiveIntegerField()),
                ('activation_month', models.PositiveIntegerField()),
                ('activation_year', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('purchase_price', models.PositiveIntegerField(default=0)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.inventoryitem')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.purchaseinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.PositiveIntegerField()),
                ('customer_name', models.CharField(blank=True, max_length=150)),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('down_payment', models.PositiveIntegerField(default=0)),
                ('sale_month', models.PositiveIntegerField()),
                ('sale_year', models.PositiveIntegerField()),
                ('is_cash_sale', models.BooleanField(default=False)),
                ('receipt_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.branch')),
            ],
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_month', models.PositiveIntegerField()),
                ('payment_year', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.PositiveIntegerField()),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.inventoryitem')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='Salesperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.branch')),
            ],
        ),
        migrations.AddField(
            model_name='receipt',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.salesperson'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.supplier'),
        ),
    ]
