# Generated by Django 6.0.6 on 2026-07-19 15:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم الفرع')),
                ('collection_commission_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='نسبة عمولة التحصيل')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'الفرع / المخزن',
                'verbose_name_plural': 'الفروع / المخازن',
                'db_table': 'salesapp_branch',
            },
        ),
        migrations.CreateModel(
            name='ClientLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('invoices_balance', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('machine_id', models.CharField(blank=True, max_length=255, null=True)),
                ('company_code', models.CharField(blank=True, max_length=10, null=True)),
                ('license_code_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('is_online_active', models.BooleanField(default=False)),
                ('online_start_date', models.DateField(blank=True, null=True)),
                ('online_expiry_date', models.DateField(blank=True, null=True)),
                ('last_checkin', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'الترخيص',
                'verbose_name_plural': 'التراخيص',
                'db_table': 'salesapp_clientlicense',
            },
        ),
        migrations.CreateModel(
            name='CompanySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('footer_text', models.CharField(default='تطبق الشروط والأحكام', max_length=250)),
                ('is_cloud_viewer', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'إعدادات الشركة',
                'verbose_name_plural': 'إعدادات الشركة',
                'db_table': 'salesapp_companysetting',
            },
        ),
        migrations.CreateModel(
            name='LicenseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('operation_type', models.CharField(default='تجديد/تفعيل', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('added_balance', models.IntegerField(default=0)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='أرشيف', max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'أرشيف الترخيص',
                'verbose_name_plural': 'أرشيف التراخيص',
                'db_table': 'salesapp_licensehistory',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'المورد',
                'verbose_name_plural': 'الموردون',
                'db_table': 'salesapp_supplier',
            },
        ),
        migrations.CreateModel(
            name='UsedLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64, unique=True)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'الكود المستخدم',
                'verbose_name_plural': 'الأكواد المستخدمة',
                'db_table': 'salesapp_usedlicense',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('expense_year', models.IntegerField()),
                ('expense_month', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.branch')),
            ],
            options={
                'verbose_name': 'المصروف',
                'verbose_name_plural': 'المصروفات',
                'db_table': 'salesapp_expense',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('initial_quantity', models.PositiveIntegerField(default=0)),
                ('initial_purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('initial_commission_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('initial_month', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('initial_year', models.PositiveIntegerField(default=2026, validators=[django.core.validators.MinValueValidator(2025)])),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='api.branch')),
            ],
            options={
                'verbose_name': 'صنف البضاعة',
                'verbose_name_plural': 'أصناف البضاعة',
                'db_table': 'salesapp_inventoryitem',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('DEFICIT', 'عجز (-)'), ('SURPLUS', 'زيادة (+)')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2025)])),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='api.inventoryitem')),
            ],
            options={
                'verbose_name': 'تسوية المخزون',
                'verbose_name_plural': 'تسويات المخزون',
                'db_table': 'salesapp_inventoryadjustment',
                'ordering': ['-year', '-month', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CommissionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('activation_month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('activation_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2025)])),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_records', to='api.inventoryitem')),
            ],
            options={
                'verbose_name': 'سجل العمولة',
                'verbose_name_plural': 'سجل العمولات',
                'db_table': 'salesapp_commissionhistory',
                'ordering': ['-activation_year', '-activation_month'],
            },
        ),
        migrations.CreateModel(
            name='PendingExternalReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(blank=True, default='', max_length=100)),
                ('source', models.CharField(max_length=20)),
                ('payload', models.JSONField()),
                ('is_processed', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_receipts', to='api.branch')),
            ],
            options={
                'verbose_name': 'الفاتورة المعلقة',
                'verbose_name_plural': 'الفواتير المعلقة',
                'db_table': 'salesapp_pendingexternalreceipt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.PositiveIntegerField()),
                ('invoice_type', models.CharField(choices=[('PURCHASE', 'فاتورة شراء'), ('RETURN', 'فاتورة مرتجع')], default='PURCHASE', max_length=20)),
                ('invoice_month', models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('invoice_year', models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(2025)])),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='api.branch')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='api.supplier')),
            ],
            options={
                'verbose_name': 'فاتورة الشراء',
                'verbose_name_plural': 'فواتير الشراء',
                'db_table': 'salesapp_purchaseinvoice',
                'ordering': ['-invoice_year', '-invoice_month', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchaseinvoiceitem_set', to='api.inventoryitem')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.purchaseinvoice')),
            ],
            options={
                'verbose_name': 'صنف فاتورة شراء',
                'verbose_name_plural': 'أصناف فواتير الشراء',
                'db_table': 'salesapp_purchaseinvoiceitem',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.PositiveIntegerField(db_index=True)),
                ('client_uuid', models.UUIDField(default=uuid.uuid4)),
                ('receipt_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('customer_name', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('down_payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('installment_system', models.CharField(blank=True, max_length=200, null=True)),
                ('sale_year', models.PositiveIntegerField(db_index=True)),
                ('sale_month', models.PositiveIntegerField(db_index=True)),
                ('is_cash_sale', models.BooleanField(default=False)),
                ('products_text', models.TextField(blank=True, null=True)),
                ('source', models.CharField(default='DESKTOP', max_length=20)),
                ('sync_action', models.CharField(default='NEW', max_length=20)),
                ('is_confirmed', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='api.branch')),
            ],
            options={
                'verbose_name': 'الفاتورة',
                'verbose_name_plural': 'الفواتير',
                'db_table': 'salesapp_receipt',
                'ordering': ['-receipt_number'],
            },
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.receipt')),
            ],
            options={
                'verbose_name': 'القسط',
                'verbose_name_plural': 'الأقساط',
                'db_table': 'salesapp_installmentpayment',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saleitem_set', to='api.inventoryitem')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='api.receipt')),
            ],
            options={
                'verbose_name': 'الصنف المباع',
                'verbose_name_plural': 'الأصناف المباعة',
                'db_table': 'salesapp_saleitem',
            },
        ),
        migrations.CreateModel(
            name='Salesperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_token', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('is_device_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salespeople', to='api.branch')),
            ],
            options={
                'verbose_name': 'المندوب',
                'verbose_name_plural': 'المناديب',
                'db_table': 'salesapp_salesperson',
            },
        ),
        migrations.AddField(
            model_name='receipt',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='api.salesperson'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['branch', 'name'], name='idx_inv_item_branch_name'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('name', 'branch'), name='uq_inventory_item_name_branch'),
        ),
        migrations.AddConstraint(
            model_name='commissionhistory',
            constraint=models.UniqueConstraint(fields=('item', 'activation_month', 'activation_year'), name='uq_comm_hist_item_date'),
        ),
        migrations.AddConstraint(
            model_name='salesperson',
            constraint=models.UniqueConstraint(fields=('name', 'branch'), name='uq_salesperson_name_branch'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['branch', 'sale_year', 'sale_month'], name='idx_receipt_branch_date'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['receipt_hash'], name='idx_receipt_hash'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(fields=('branch', 'receipt_number'), name='uq_receipt_branch_number'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoice',
            constraint=models.UniqueConstraint(fields=('branch', 'invoice_number', 'supplier'), name='uq_pur_inv_branch_num_supp'),
        ),
    ]
