# Generated by Django 6.0.6 on 2026-07-01 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlicense',
            name='tenant',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='client_licenses', to='api.tenant'),
        ),
        migrations.AlterField(
            model_name='licensehistory',
            name='tenant',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='license_histories', to='api.tenant'),
        ),
        migrations.AlterField(
            model_name='usedlicense',
            name='tenant',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='used_licenses', to='api.tenant'),
        ),
    ]
