# Generated by Django 6.0.6 on 2026-07-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='collection_commission_rate',
        ),
        migrations.AddField(
            model_name='companysetting',
            name='collection_commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='نسبة عمولة التحصيل'),
        ),
    ]
