# Generated by Django 6.0.6 on 2026-07-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_branch_collection_commission_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysetting',
            name='zoom_level',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='مستوى التكبير'),
        ),
    ]
