# Generated by Django 6.0.6 on 2026-06-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_receipt_phone_number_alter_receipt_receipt_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='phone_number',
            new_name='customer_phone',
        ),
        migrations.AddField(
            model_name='receipt',
            name='customer_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='customer_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
