# Generated by Django 6.0.6 on 2026-07-08 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_clientlicense_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlicense',
            name='tenant',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='client_licenses', to='api.tenant'),
        ),
        migrations.AlterField(
            model_name='clouduser',
            name='tenant',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='cloud_users', to='api.tenant'),
        ),
        migrations.AlterField(
            model_name='companysetting',
            name='tenant',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='company_setting', to='api.tenant'),
        ),
        migrations.AlterField(
            model_name='licensehistory',
            name='tenant',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='license_histories', to='api.tenant'),
        ),
        migrations.AlterField(
            model_name='usedlicense',
            name='tenant',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='used_licenses', to='api.tenant'),
        ),
    ]
