# Generated by Django 5.2.7 on 2025-12-22 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(blank=True, max_length=100, null=True, verbose_name='القائم بالعملية')),
                ('action_type', models.CharField(choices=[('CREATE', 'إضافة جديد'), ('UPDATE', 'تعديل بيانات'), ('DELETE', 'حذف'), ('SYNC', 'مزامنة بيانات'), ('LOGIN', 'تسجيل دخول')], max_length=20, verbose_name='نوع العملية')),
                ('model_name', models.CharField(max_length=50, verbose_name='القسم')),
                ('details', models.TextField(blank=True, null=True, verbose_name='التفاصيل')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سجل النشاطات',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الفرع')),
            ],
        ),
        migrations.CreateModel(
            name='ClientLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(choices=[(1, 'تجربة مجانية (Trial 14 Days)'), (2, 'طباعة فقط - سنة واحدة'), (3, 'طباعة فقط - مدى الحياة'), (4, 'إدارة كاملة - سنة واحدة'), (5, 'إدارة كاملة - 3 سنوات'), (6, 'إدارة كاملة - 5 سنوات'), (7, 'إدارة كاملة - مدى الحياة (VIP)'), (8, 'إضافة الأونلاين - سنة'), (9, 'إضافة الأونلاين - 5 سنوات'), (10, 'كود شحن (100 فاتورة)'), (11, 'كود شحن (300 فاتورة)'), (12, 'كود شحن (500 فاتورة)'), (13, 'كود شحن (1000 فاتورة)'), (14, 'كود شحن (3000 فاتورة)'), (15, 'كود شحن (5000 فاتورة)')], verbose_name='نوع الباقة الحالية')),
                ('start_date', models.DateField(verbose_name='تاريخ تفعيل الباقة')),
                ('invoices_balance', models.PositiveIntegerField(default=0, verbose_name='رصيد الفواتير المتبقي')),
                ('is_active', models.BooleanField(default=True, verbose_name='حالة الاشتراك')),
                ('machine_id', models.CharField(max_length=255, verbose_name='بصمة الجهاز المسجل')),
                ('last_checkin', models.DateTimeField(auto_now=True, verbose_name='آخر نشاط')),
            ],
        ),
        migrations.CreateModel(
            name='CompanySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الشركة')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='وصف الشركة')),
                ('phone1', models.CharField(max_length=20, verbose_name='رقم تليفون 1')),
                ('phone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم تليفون 2')),
                ('footer_text', models.CharField(default='تطبق الشروط والأحكام', max_length=250, verbose_name='الفوتر')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('expense_year', models.IntegerField()),
                ('expense_month', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesapp.branch')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الصنف')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية المتاحة')),
                ('purchase_price', models.PositiveIntegerField(default=0, verbose_name='سعر الشراء')),
                ('salesperson_commission_amount', models.PositiveIntegerField(default=0, verbose_name='قيمة عمولة المندوب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salesapp.branch', verbose_name='مخزن الفرع')),
            ],
            options={
                'unique_together': {('name', 'branch')},
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('DESKTOP', 'الكمبيوتر الرئيسي'), ('MOBILE', 'تطبيق المندوب')], default='DESKTOP', max_length=20, verbose_name='المصدر')),
                ('receipt_number', models.PositiveIntegerField(db_index=True, verbose_name='رقم الوصل')),
                ('customer_name', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='اسم العميل')),
                ('products_text', models.TextField(blank=True, null=True, verbose_name='نص المنتجات (للطباعة)')),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='رقم الهاتف')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('area', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='المنطقة')),
                ('total_amount', models.PositiveIntegerField(default=0, verbose_name='الإجمالي')),
                ('down_payment', models.PositiveIntegerField(default=0, verbose_name='المقدم')),
                ('installment_system', models.CharField(blank=True, max_length=200, verbose_name='وصف نظام القسط')),
                ('sale_year', models.PositiveIntegerField(db_index=True, verbose_name='سنة البيع')),
                ('sale_month', models.PositiveIntegerField(db_index=True, verbose_name='شهر البيع')),
                ('is_cash_sale', models.BooleanField(default=False, verbose_name='بيع كاش؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salesapp.branch', verbose_name='الفرع')),
            ],
            options={
                'ordering': ['-receipt_number'],
            },
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='تاريخ الدفعة المستحقة')),
                ('amount', models.PositiveIntegerField(verbose_name='المبلغ')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='salesapp.receipt', verbose_name='الوصل التابع له')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('unit_price', models.PositiveIntegerField(verbose_name='سعر الوحدة')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salesapp.inventoryitem', verbose_name='الصنف')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='salesapp.receipt', verbose_name='الوصل التابع له')),
            ],
        ),
        migrations.CreateModel(
            name='Salesperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الموظف')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salesapp.branch', verbose_name='الفرع التابع له')),
            ],
            options={
                'unique_together': {('name', 'branch')},
            },
        ),
        migrations.AddField(
            model_name='receipt',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='salesapp.salesperson', verbose_name='المندوب'),
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'شراء / إضافة كمية جديدة'), ('RETURN_TO_FACTORY', 'إرجاع للمصنع / المورد')], max_length=20, verbose_name='نوع الحركة')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحركة')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salesapp.inventoryitem', verbose_name='الصنف')),
            ],
            options={
                'verbose_name': 'حركة مخزنية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='receipt',
            unique_together={('branch', 'receipt_number')},
        ),
    ]
