# Generated by Django 5.2.7 on 2025-12-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64, unique=True, verbose_name='بصمة الكود')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
