# Generated by Django 5.2.7 on 2025-12-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0002_usedlicense'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('operation_type', models.CharField(default='تجديد/تفعيل', max_length=50, verbose_name='نوع العملية')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('added_balance', models.IntegerField(default=0, verbose_name='الرصيد المضاف')),
                ('archived_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ العملية')),
                ('status', models.CharField(default='أرشيف', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='clientlicense',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الصلاحية'),
        ),
        migrations.AddField(
            model_name='clientlicense',
            name='is_online_active',
            field=models.BooleanField(default=False, verbose_name='حالة الأونلاين'),
        ),
        migrations.AddField(
            model_name='clientlicense',
            name='online_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='انتهاء الأونلاين'),
        ),
        migrations.AddField(
            model_name='clientlicense',
            name='online_product_id',
            field=models.IntegerField(default=0, verbose_name='كود باقة الأونلاين'),
        ),
        migrations.AddField(
            model_name='clientlicense',
            name='online_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='بداية الأونلاين'),
        ),
        migrations.AlterField(
            model_name='clientlicense',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='حالة الاشتراك'),
        ),
        migrations.AlterField(
            model_name='clientlicense',
            name='machine_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='بصمة الجهاز المسجل'),
        ),
        migrations.AlterField(
            model_name='clientlicense',
            name='product_id',
            field=models.IntegerField(choices=[(1, 'تجربة مجانية (Trial 14 Days)'), (2, 'طباعة فقط - سنة واحدة'), (3, 'طباعة فقط - مدى الحياة'), (4, 'إدارة كاملة - سنة واحدة'), (5, 'إدارة كاملة - 3 سنوات'), (6, 'إدارة كاملة - 5 سنوات'), (7, 'إدارة كاملة - مدى الحياة (VIP)'), (8, 'إضافة الأونلاين - سنة'), (9, 'إضافة الأونلاين - 5 سنوات'), (10, 'كود شحن (100 فاتورة)'), (11, 'كود شحن (300 فاتورة)'), (12, 'كود شحن (500 فاتورة)'), (13, 'كود شحن (1000 فاتورة)'), (14, 'كود شحن (3000 فاتورة)'), (15, 'كود شحن (5000 فاتورة)')], default=1, verbose_name='نوع الباقة الحالية'),
        ),
        migrations.AlterField(
            model_name='clientlicense',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ تفعيل الباقة'),
        ),
    ]
