# Generated by Django 5.2.7 on 2025-12-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0003_licensehistory_clientlicense_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(choices=[('Receipt', 'Receipt'), ('InventoryItem', 'InventoryItem'), ('Salesperson', 'Salesperson'), ('Expense', 'Expense'), ('StockTransaction', 'StockTransaction')], max_length=50)),
                ('record_id', models.IntegerField(verbose_name='ID العنصر المحذوف')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receipt',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
    ]
