# Generated by Django 5.2.7 on 2026-01-24 18:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0004_syncdeletionlog_branch_is_synced_expense_is_synced_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientlicense',
            name='online_product_id',
        ),
        migrations.AddField(
            model_name='clientlicense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientlicense',
            name='license_code_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='توقيع الكود'),
        ),
        migrations.AlterField(
            model_name='clientlicense',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='clientlicense',
            name='invoices_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='رصيد الفواتير'),
        ),
        migrations.AlterField(
            model_name='clientlicense',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='حالة الكود'),
        ),
        migrations.AlterField(
            model_name='clientlicense',
            name='is_online_active',
            field=models.BooleanField(default=False, verbose_name='يدعم الأونلاين'),
        ),
        migrations.AlterField(
            model_name='clientlicense',
            name='machine_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الجهاز'),
        ),
        migrations.AlterField(
            model_name='clientlicense',
            name='product_id',
            field=models.IntegerField(choices=[(1, 'تجربة مجانية (Trial 14 Days)'), (2, 'طباعة فقط - سنة واحدة'), (3, 'طباعة فقط - مدى الحياة'), (4, 'إدارة كاملة - سنة واحدة'), (5, 'إدارة كاملة - 3 سنوات'), (6, 'إدارة كاملة - 5 سنوات'), (7, 'إدارة كاملة - مدى الحياة (VIP)'), (8, 'إضافة الأونلاين - سنة'), (9, 'إضافة الأونلاين - 5 سنوات'), (10, 'كود شحن (100 فاتورة)'), (11, 'كود شحن (300 فاتورة)'), (12, 'كود شحن (500 فاتورة)'), (13, 'كود شحن (1000 فاتورة)'), (14, 'كود شحن (3000 فاتورة)'), (15, 'كود شحن (5000 فاتورة)')], default=1, verbose_name='نوع الباقة'),
        ),
        migrations.AlterField(
            model_name='clientlicense',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التفعيل'),
        ),
    ]
