# Generated by Django 5.2.7 on 2026-04-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0005_remove_clientlicense_online_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlicense',
            name='product_id',
            field=models.IntegerField(choices=[(1, 'تجربة مجانية (Trial 30 Days)'), (2, 'طباعة فقط - سنة واحدة'), (3, 'طباعة فقط - مدى الحياة'), (4, 'إدارة كاملة - سنة واحدة'), (5, 'إدارة كاملة - 3 سنوات'), (6, 'إدارة كاملة - 5 سنوات'), (7, 'إدارة كاملة - مدى الحياة (VIP)'), (8, 'إضافة الأونلاين - سنة'), (9, 'إضافة الأونلاين - 5 سنوات'), (10, 'كود شحن (100 فاتورة)'), (11, 'كود شحن (300 فاتورة)'), (12, 'كود شحن (500 فاتورة)'), (13, 'كود شحن (1000 فاتورة)'), (14, 'كود شحن (3000 فاتورة)'), (15, 'كود شحن (5000 فاتورة)')], default=1, verbose_name='نوع الباقة'),
        ),
    ]
