# Generated by Django 5.2.7 on 2026-04-23 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0006_alter_clientlicense_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='اسم المورد / المصنع')),
                ('is_synced', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='initial_commission_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='العمولة الابتدائية (تاريخية)'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='initial_purchase_price',
            field=models.PositiveIntegerField(default=0, verbose_name='سعر الشراء الابتدائي (تاريخي)'),
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=50, verbose_name='رقم الفاتورة')),
                ('invoice_type', models.CharField(choices=[('PURCHASE', 'فاتورة شراء (إضافة للمخزن)'), ('RETURN', 'فاتورة مرتجع (خصم من المخزن)')], default='PURCHASE', max_length=20, verbose_name='نوع الفاتورة')),
                ('invoice_month', models.PositiveIntegerField(db_index=True, verbose_name='شهر الفاتورة')),
                ('invoice_year', models.PositiveIntegerField(db_index=True, verbose_name='سنة الفاتورة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_synced', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salesapp.branch', verbose_name='الفرع')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salesapp.supplier', verbose_name='المورد')),
            ],
            options={
                'ordering': ['-invoice_year', '-invoice_month', '-id'],
                'unique_together': {('branch', 'invoice_number', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('purchase_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='السعر بالفاتورة')),
                ('commission_amount', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='العمولة بالفاتورة')),
                ('is_synced', models.BooleanField(default=False)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salesapp.inventoryitem', verbose_name='الصنف')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='salesapp.purchaseinvoice')),
            ],
        ),
    ]
