# Generated by Django 5.2.7 on 2026-04-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0007_supplier_inventoryitem_initial_commission_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_number',
            field=models.PositiveIntegerField(unique=True, verbose_name='رقم الفاتورة'),
        ),
    ]
