# Generated by Django 5.2.7 on 2026-04-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0008_alter_purchaseinvoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receipt_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='بصمة الفاتورة'),
        ),
    ]
