# Generated by Django 5.2.7

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone
from django.db.models import Sum

# 🔴 استدعاء دوال التشفير للفواتير والتراخيص
from salesapp.security_utils import generate_receipt_signature, generate_record_signature 

# ===============================================
# دالة نقل وتأمين البيانات (الكوبري + التشفير الشامل)
# ===============================================
# ===============================================
# دالة نقل وتأمين البيانات (الكوبري + التوجيه الإجباري للقواعد)
# ===============================================
def secure_data_transfer(apps, schema_editor):
    InventoryItem = apps.get_model('salesapp', 'InventoryItem')
    Receipt = apps.get_model('salesapp', 'Receipt')
    SaleItem = apps.get_model('salesapp', 'SaleItem')
    StockTransaction = apps.get_model('salesapp', 'StockTransaction')
    ClientLicense = apps.get_model('salesapp', 'ClientLicense')

    # 1. إعدام حركات المخزن القديمة (في قاعدة default)
    StockTransaction.objects.using('default').all().delete()

    # 2. معالجة بيانات الأصناف 
    for item in InventoryItem.objects.using('default').all():
        branch_id = item.branch_id
        
        oldest_receipt = Receipt.objects.using('default').filter(branch_id=branch_id).order_by('sale_year', 'sale_month').first()
        if oldest_receipt:
            item.initial_month = oldest_receipt.sale_month
            item.initial_year = oldest_receipt.sale_year
        else:
            now = timezone.now()
            item.initial_month = now.month
            item.initial_year = now.year

        total_sold = SaleItem.objects.using('default').filter(inventory_item=item).aggregate(total=Sum('quantity'))['total'] or 0
        current_qty = getattr(item, 'quantity', 0)
        item.initial_quantity = current_qty + total_sold
        
        item.initial_purchase_price = getattr(item, 'purchase_price', 0)
        item.initial_commission_amount = getattr(item, 'salesperson_commission_amount', 0)
        item.save(using='default')

    # 3. تأمين وتشفير الفواتير القديمة (V1)
    for receipt in Receipt.objects.using('default').all():
        receipt.receipt_hash = generate_receipt_signature(
            receipt.receipt_number,
            receipt.total_amount,
            receipt.sale_month,
            receipt.sale_year
        )
        receipt.save(using='default')

    # 4. 🔴 تأمين وتشفير التراخيص القديمة (توجيه إجباري لقاعدة System)
    # استخدمنا try/except لتجنب الخطأ إذا لم تكن قاعدة بيانات النظام مهيأة بعد
    try:
        for license in ClientLicense.objects.using('system').all():
            license.license_code_hash = generate_record_signature(
                license.expiry_date,
                license.invoices_balance,
                license.machine_id,
                license.product_id,
                license.is_active
            )
            license.save(using='system')
    except Exception as e:
        print(f"\n[تنبيه] تم تخطي تحديث التراخيص (ربما لأن قاعدة system غير جاهزة بعد): {e}")

def reverse_transfer(apps, schema_editor):
    pass
# ===============================================
def reverse_transfer(apps, schema_editor):
    pass
# ===============================================

class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0009_receipt_receipt_hash'),
    ]

    operations = [
        # 1. إنشاء الحقول الجديدة (مرحلة التوسعة)
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='initial_month',
            field=models.PositiveIntegerField(default=1, verbose_name='شهر البداية'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='initial_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='الكمية الافتتاحية'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='initial_year',
            field=models.PositiveIntegerField(default=2026, verbose_name='سنة البداية'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='initial_commission_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='المندبة الابتدائية'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='initial_purchase_price',
            field=models.PositiveIntegerField(default=0, verbose_name='سعر الشراء الافتتاحي'),
        ),

        # 2. تشغيل سكريبت نقل البيانات وتأمين الفواتير والتراخيص (الكوبري)
        migrations.RunPython(secure_data_transfer, reverse_transfer),

        # 3. إعدام الحقول القديمة (مرحلة التنظيف)
        migrations.RemoveField(
            model_name='inventoryitem',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='salesperson_commission_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoiceitem',
            name='commission_amount',
        ),

        # 4. بناء الجداول الجديدة للإصدار الثاني
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('DEFICIT', 'عجز (-)'), ('SURPLUS', 'زيادة (+)')], max_length=10, verbose_name='نوع التسوية')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='السبب / ملاحظات')),
                ('month', models.PositiveIntegerField(verbose_name='شهر التسوية')),
                ('year', models.PositiveIntegerField(verbose_name='سنة التسوية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='salesapp.inventoryitem', verbose_name='المنتج')),
            ],
            options={
                'ordering': ['-year', '-month', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CommissionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_amount', models.PositiveIntegerField(verbose_name='المندبة الجديدة')),
                ('activation_month', models.PositiveIntegerField(verbose_name='شهر التفعيل')),
                ('activation_year', models.PositiveIntegerField(verbose_name='سنة التفعيل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_records', to='salesapp.inventoryitem', verbose_name='المنتج')),
            ],
            options={
                'ordering': ['-activation_year', '-activation_month'],
                'unique_together': {('item', 'activation_month', 'activation_year')},
            },
        ),
    ]