# Generated by Django 5.2.7 on 2026-05-12 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0010_alter_inventoryitem_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockTransaction',
        ),
    ]
