# Generated by Django 4.2.30 on 2026-06-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0011_delete_stocktransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlicense',
            name='product_id',
            field=models.IntegerField(choices=[(1, 'تجربة مجانية (Trial 60 Days)'), (2, 'طباعة فقط - سنة واحدة'), (3, 'طباعة فقط - مدى الحياة'), (4, 'إدارة كاملة - سنة واحدة'), (5, 'إدارة كاملة - 3 سنوات'), (6, 'إدارة كاملة - 5 سنوات'), (7, 'إدارة كاملة - مدى الحياة (VIP)'), (8, 'إضافة الأونلاين - سنة'), (9, 'إضافة الأونلاين - 5 سنوات'), (10, 'كود شحن (100 فاتورة)'), (11, 'كود شحن (300 فاتورة)'), (12, 'كود شحن (500 فاتورة)'), (13, 'كود شحن (1000 فاتورة)'), (14, 'كود شحن (3000 فاتورة)'), (15, 'كود شحن (5000 فاتورة)'), (16, 'كود الطوارئ (استعادة وضبط)')], default=1, verbose_name='نوع الباقة'),
        ),
    ]
