# Generated by Django 4.2.30 on 2026-06-19 01:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0012_alter_clientlicense_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='device_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, verbose_name='توكن الجهاز'),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='is_device_active',
            field=models.BooleanField(default=False, verbose_name='الجهاز مفعل؟'),
        ),
    ]
