# Generated by Django 4.2.30 on 2026-06-19 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0013_salesperson_device_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingExternalReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('CLOUD', 'السحابة (أونلاين)'), ('USB', 'سلك الـ USB'), ('FILE', 'ملف JSON')], max_length=20, verbose_name='المصدر')),
                ('payload', models.JSONField(verbose_name='بيانات الفاتورة (JSON)')),
                ('is_processed', models.BooleanField(default=False, verbose_name='تم المراجعة والإضافة؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الوصول')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesapp.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'فاتورة خارجية معلقة',
                'verbose_name_plural': 'الفواتير الخارجية المعلقة',
                'ordering': ['-created_at'],
            },
        ),
    ]
