# Generated by Django 4.2.30 on 2026-06-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0014_pendingexternalreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingexternalreceipt',
            name='batch_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='معرف التصدير'),
        ),
    ]
