# Generated by Django 4.2.30 on 2026-06-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0015_pendingexternalreceipt_batch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='is_cash_sale',
            field=models.BooleanField(default=False, verbose_name='كاش فقط'),
        ),
    ]
