# Generated by Django 4.2.30 on 2026-06-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0016_alter_receipt_is_cash_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='اسم المستخدم')),
                ('password', models.CharField(max_length=255, verbose_name='كلمة المرور')),
                ('role', models.CharField(choices=[('VIEWER', 'مشاهد'), ('CASHIER', 'كاشير فرعي')], default='VIEWER', max_length=50, verbose_name='الصلاحية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
