# Generated by Django 4.2.30 on 2026-06-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0017_clouduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlicense',
            name='company_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='كود الشركة (للأونلاين)'),
        ),
    ]
