# Generated by Django 4.2.30 on 2026-06-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0018_clientlicense_company_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysetting',
            name='is_cloud_viewer',
            field=models.BooleanField(default=False, verbose_name='جهاز مشاهد سحابي'),
        ),
    ]
