# Generated by Django 4.2.30 on 2026-06-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0019_companysetting_is_cloud_viewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='cloud_password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='كلمة المرور السحابية'),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='cloud_username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم المستخدم السحابي'),
        ),
    ]
