# Generated by Django 4.2.30 on 2026-06-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0020_salesperson_cloud_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='is_confirmed',
            field=models.BooleanField(default=True, verbose_name='تم التأكيد (للمدير)'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='sync_action',
            field=models.CharField(default='NEW', max_length=20, verbose_name='إجراء المزامنة'),
        ),
    ]
