# Generated by Django 6.0 on 2025-12-21 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم العميل')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('machine_id', models.CharField(max_length=100, unique=True, verbose_name='بصمة الجهاز (Machine ID)')),
                ('store_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المحل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(choices=[(1, 'تجربة مجانية (Trial 14 Days)'), (2, 'طباعة فقط - سنة واحدة'), (3, 'طباعة فقط - مدى الحياة'), (4, 'إدارة كاملة - سنة واحدة'), (5, 'إدارة كاملة - 3 سنوات'), (6, 'إدارة كاملة - 5 سنوات'), (7, 'إدارة كاملة - مدى الحياة (VIP)'), (8, 'إضافة الأونلاين - سنة'), (9, 'إضافة الأونلاين - 5 سنوات'), (10, 'كود شحن (100 فاتورة)'), (11, 'كود شحن (300 فاتورة)'), (12, 'كود شحن (500 فاتورة)'), (13, 'كود شحن (1000 فاتورة)'), (14, 'كود شحن (3000 فاتورة)'), (15, 'كود شحن (5000 فاتورة)'), (16, 'خاص / احتياطي (Reserved)')], verbose_name='نوع الباقة')),
                ('generated_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التوليد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='licenses.client', verbose_name='العميل')),
            ],
        ),
    ]
