# Generated by Django 6.0 on 2025-12-21 19:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='is_active',
        ),
        migrations.AddField(
            model_name='license',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ بداية الترخيص'),
        ),
        migrations.AlterField(
            model_name='client',
            name='machine_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='بصمة الجهاز'),
        ),
        migrations.AlterField(
            model_name='license',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licenses.client'),
        ),
        migrations.AlterField(
            model_name='license',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='product_id',
            field=models.IntegerField(choices=[(1, 'تجربة مجانية (Trial 14 Days)'), (2, 'طباعة فقط - سنة واحدة'), (3, 'طباعة فقط - مدى الحياة'), (4, 'إدارة كاملة - سنة واحدة'), (5, 'إدارة كاملة - 3 سنوات'), (6, 'إدارة كاملة - 5 سنوات'), (7, 'إدارة كاملة - مدى الحياة (VIP)'), (8, 'إضافة الأونلاين - سنة'), (9, 'إضافة الأونلاين - 5 سنوات'), (10, 'كود شحن (100 فاتورة)'), (11, 'كود شحن (300 فاتورة)'), (12, 'كود شحن (500 فاتورة)'), (13, 'كود شحن (1000 فاتورة)'), (14, 'كود شحن (3000 فاتورة)'), (15, 'كود شحن (5000 فاتورة)'), (16, 'خاص / احتياطي')], verbose_name='نوع الباقة'),
        ),
    ]
