# Generated by Django 6.0 on 2025-12-21 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_remove_license_is_active_license_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='حظر هذا الجهاز (Blacklist)'),
        ),
        migrations.AddField(
            model_name='license',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='license',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات فنية (سري)'),
        ),
        migrations.AddField(
            model_name='license',
            name='price',
            field=models.IntegerField(default=0, verbose_name='المبلغ المدفوع (جنية)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل'),
        ),
        migrations.AlterField(
            model_name='client',
            name='machine_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='بصمة الجهاز (Machine ID)'),
        ),
        migrations.AlterField(
            model_name='license',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='licenses.client', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='license',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='license',
            name='generated_code',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='كود التفعيل'),
        ),
    ]
