# Generated by Django 6.0 on 2025-12-23 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=255, unique=True, verbose_name='بصمة الجهاز')),
                ('client_name', models.CharField(blank=True, max_length=150, verbose_name='اسم العميل')),
                ('is_active', models.BooleanField(default=True, verbose_name='مسموح له بالمزامنة؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
            ],
        ),
        migrations.CreateModel(
            name='ServerBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_machine_id', models.CharField(db_index=True, max_length=255)),
                ('local_id', models.IntegerField(verbose_name='ID الفرع المحلي')),
                ('name', models.CharField(max_length=150)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('source_machine_id', 'local_id')},
            },
        ),
        migrations.CreateModel(
            name='ServerInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_machine_id', models.CharField(db_index=True, max_length=255)),
                ('local_id', models.IntegerField(verbose_name='ID المنتج المحلي')),
                ('local_branch_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salesperson_commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('source_machine_id', 'local_id')},
            },
        ),
        migrations.CreateModel(
            name='ServerReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_machine_id', models.CharField(db_index=True, max_length=255)),
                ('local_id', models.IntegerField(verbose_name='ID الفاتورة المحلي pk')),
                ('receipt_number', models.PositiveIntegerField(verbose_name='رقم الفاتورة المطبوع')),
                ('local_branch_id', models.IntegerField()),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('area', models.CharField(blank=True, max_length=150)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('installment_system', models.CharField(blank=True, max_length=255)),
                ('local_salesperson_id', models.IntegerField(blank=True, null=True)),
                ('sale_year', models.IntegerField()),
                ('sale_month', models.IntegerField()),
                ('is_cash_sale', models.BooleanField(default=False)),
                ('products_text', models.TextField(blank=True, null=True)),
                ('created_at_local', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإنشاء عند العميل')),
                ('synced_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الوصول للسيرفر')),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source_machine_id', 'receipt_number'], name='sync_api_se_source__0049ce_idx'), models.Index(fields=['synced_at'], name='sync_api_se_synced__887700_idx')],
                'unique_together': {('source_machine_id', 'local_id')},
            },
        ),
        migrations.CreateModel(
            name='ServerInstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sync_api.serverreceipt')),
            ],
        ),
        migrations.CreateModel(
            name='ServerSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_product_id', models.IntegerField(verbose_name='ID المنتج الأصلي')),
                ('product_name_snapshot', models.CharField(max_length=255, verbose_name='اسم المنتج وقت البيع')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sync_api.serverreceipt')),
            ],
        ),
        migrations.CreateModel(
            name='ServerSalesperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_machine_id', models.CharField(db_index=True, max_length=255)),
                ('local_id', models.IntegerField()),
                ('local_branch_id', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('source_machine_id', 'local_id')},
            },
        ),
    ]
