# Generated by Django 6.0 on 2025-12-23 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerCompanySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_machine_id', models.CharField(db_index=True, max_length=255)),
                ('local_id', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=100, verbose_name='اسم الشركة')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('footer_text', models.CharField(blank=True, max_length=250, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات شركة عميل',
            },
        ),
        migrations.CreateModel(
            name='ServerExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_machine_id', models.CharField(db_index=True, max_length=255)),
                ('local_id', models.IntegerField(verbose_name='ID المصروف المحلي')),
                ('local_branch_id', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('expense_year', models.IntegerField()),
                ('expense_month', models.IntegerField()),
                ('created_at_local', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerStockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_machine_id', models.CharField(db_index=True, max_length=255)),
                ('local_id', models.IntegerField(verbose_name='ID الحركة المحلي')),
                ('local_product_id', models.IntegerField()),
                ('product_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('transaction_type', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('created_at_local', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='serverreceipt',
            options={'ordering': ['-created_at_local']},
        ),
        migrations.RemoveIndex(
            model_name='serverreceipt',
            name='sync_api_se_source__0049ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='serverreceipt',
            name='sync_api_se_synced__887700_idx',
        ),
        migrations.RenameField(
            model_name='serverbranch',
            old_name='last_modified',
            new_name='synced_at',
        ),
        migrations.RenameField(
            model_name='serverinventoryitem',
            old_name='last_modified',
            new_name='synced_at',
        ),
        migrations.RenameField(
            model_name='serversalesperson',
            old_name='last_modified',
            new_name='synced_at',
        ),
        migrations.RemoveField(
            model_name='serverbranch',
            name='created_at',
        ),
        migrations.AddField(
            model_name='serverinventoryitem',
            name='created_at_local',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serverinventoryitem',
            name='local_branch_id',
            field=models.IntegerField(verbose_name='ID المخزن'),
        ),
        migrations.AlterField(
            model_name='serverinventoryitem',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='serverinventoryitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='serverreceipt',
            name='created_at_local',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serverreceipt',
            name='local_id',
            field=models.IntegerField(verbose_name='ID الفاتورة المحلي'),
        ),
        migrations.AlterField(
            model_name='serverreceipt',
            name='receipt_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='serverreceipt',
            name='synced_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='serversaleitem',
            name='local_product_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='serversaleitem',
            name='product_name_snapshot',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='serversalesperson',
            name='local_branch_id',
            field=models.IntegerField(verbose_name='ID فرع الموظف'),
        ),
        migrations.AlterField(
            model_name='serversalesperson',
            name='local_id',
            field=models.IntegerField(verbose_name='ID الموظف المحلي'),
        ),
        migrations.AlterField(
            model_name='serversalesperson',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='servercompanysetting',
            unique_together={('source_machine_id', 'local_id')},
        ),
        migrations.AlterUniqueTogether(
            name='serverexpense',
            unique_together={('source_machine_id', 'local_id')},
        ),
        migrations.AlterUniqueTogether(
            name='serverstocktransaction',
            unique_together={('source_machine_id', 'local_id')},
        ),
        migrations.RemoveField(
            model_name='serverreceipt',
            name='last_modified',
        ),
    ]
