# Generated by Django 6.0 on 2026-06-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_api', '0002_servercompanysetting_serverexpense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverlicense',
            name='is_online_active',
            field=models.BooleanField(default=False, verbose_name='مسموح له بالمزامنة الأونلاين؟'),
        ),
        migrations.AddField(
            model_name='serverlicense',
            name='online_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الأونلاين'),
        ),
        migrations.AddField(
            model_name='serverreceipt',
            name='receipt_hash',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='هاش الفاتورة'),
        ),
    ]
