# Generated by Django 6.0 on 2026-06-19 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_api', '0003_serverlicense_is_online_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverreceipt',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='تم التأكيد'),
        ),
    ]
