# Generated by Django 6.0 on 2026-06-19 01:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_api', '0004_serverreceipt_is_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileProvisionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
