# Generated by Django 6.0 on 2026-06-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_api', '0005_mobileprovisiontoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverlicense',
            name='company_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='كود الشركة'),
        ),
        migrations.CreateModel(
            name='ServerCloudUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_machine_id', models.CharField(db_index=True, max_length=255)),
                ('local_id', models.IntegerField(verbose_name='ID المستخدم المحلي')),
                ('username', models.CharField(max_length=150)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(default='VIEWER', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مستخدم سحابي (فرعي)',
                'unique_together': {('source_machine_id', 'local_id')},
            },
        ),
    ]
