# Generated by Django 6.0 on 2026-06-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync_api', '0006_serverlicense_company_code_serverclouduser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serverclouduser',
            options={'verbose_name': 'مستخدم سحابي (فرعي)', 'verbose_name_plural': 'مستخدمي السحابة (فروع)'},
        ),
        migrations.AlterModelOptions(
            name='servercompanysetting',
            options={'verbose_name': 'إعدادات شركة عميل', 'verbose_name_plural': 'إعدادات شركات العملاء'},
        ),
        migrations.AlterUniqueTogether(
            name='serverreceipt',
            unique_together=set(),
        ),
    ]
