# Generated by Django 6.0 on 2026-06-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_api', '0007_alter_serverclouduser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serversalesperson',
            name='cloud_password',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='كلمة مرور السحابة'),
        ),
        migrations.AddField(
            model_name='serversalesperson',
            name='cloud_username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم مستخدم السحابة'),
        ),
    ]
