# Generated by Django 6.0 on 2026-06-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_api', '0008_serversalesperson_cloud_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverreceipt',
            name='sync_action',
            field=models.CharField(default='NEW', max_length=20, verbose_name='Action from Mobile'),
        ),
    ]
