# Generated by Django 6.0 on 2026-06-24 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_api', '0009_serverreceipt_sync_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerCommissionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_machine_id', models.CharField(db_index=True, max_length=255)),
                ('local_id', models.IntegerField(verbose_name='ID السجل المحلي')),
                ('local_salesperson_id', models.IntegerField(verbose_name='ID المندوب المحلي')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قيمة العمولة')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='السبب')),
                ('commission_date', models.DateField(blank=True, null=True, verbose_name='تاريخ العمولة')),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سجل عمولة',
                'verbose_name_plural': 'سجلات العمولات',
                'unique_together': {('source_machine_id', 'local_id')},
            },
        ),
        migrations.CreateModel(
            name='ServerPurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_machine_id', models.CharField(db_index=True, max_length=255)),
                ('local_id', models.IntegerField(verbose_name='ID الفاتورة المحلي')),
                ('invoice_number', models.PositiveIntegerField(verbose_name='رقم الفاتورة')),
                ('invoice_month', models.IntegerField(verbose_name='شهر الفاتورة')),
                ('invoice_year', models.IntegerField(verbose_name='سنة الفاتورة')),
                ('invoice_type', models.CharField(choices=[('PURCHASE', 'مشتريات'), ('RETURN', 'مرتجع')], default='PURCHASE', max_length=20, verbose_name='نوع الفاتورة')),
                ('local_supplier_id', models.IntegerField(blank=True, null=True, verbose_name='ID المورد المحلي')),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'فاتورة مشتريات',
                'verbose_name_plural': 'فواتير المشتريات',
                'unique_together': {('source_machine_id', 'local_id')},
            },
        ),
        migrations.CreateModel(
            name='ServerPurchaseInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_product_id', models.IntegerField(verbose_name='ID الصنف المحلي')),
                ('product_name_snapshot', models.CharField(blank=True, max_length=255, verbose_name='اسم الصنف وقت الشراء')),
                ('quantity', models.IntegerField(verbose_name='الكمية')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='سعر الشراء')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sync_api.serverpurchaseinvoice')),
            ],
            options={
                'verbose_name': 'بند فاتورة مشتريات',
                'verbose_name_plural': 'بنود فواتير المشتريات',
            },
        ),
        migrations.CreateModel(
            name='ServerSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_machine_id', models.CharField(db_index=True, max_length=255)),
                ('local_id', models.IntegerField(verbose_name='ID المورد المحلي')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المورد')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم التليفون')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان')),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردين',
                'unique_together': {('source_machine_id', 'local_id')},
            },
        ),
    ]
