"""
Django settings for sales project.
Generated by 'django-admin startproject' using Django 5.2.7.
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# Handle PyInstaller _MEIPASS path for frozen executables
if getattr(sys, 'frozen', False):
    BASE_DIR = Path(sys._MEIPASS)
else:
    BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&8-%+ycmk0+y$!=x1*2@q1es&bt#2a_gzhy-0w(ra#^r0u)13$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    'https://jargonal-colourationally-buddy.ngrok-free.dev',
]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'salesapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Static files optimization
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'salesapp.middleware.LicenseEnforcementMiddleware',
]

ROOT_URLCONF = 'sales.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'salesapp.context_processors.license_plan_context',

            ],
        },
    },
]

WSGI_APPLICATION = 'sales.wsgi.application'

# =========================================================
# 🗄️ DATABASE CONFIGURATION (Dual-File Split)
# =========================================================

# =========================================================
# 🗄️ DATABASE CONFIGURATION (Encrypted Hybrid Runtime)
# =========================================================
import tempfile # 🔴 استدعاء جديد للملفات المؤقتة

LOCAL_APP_DATA = os.environ.get('LOCALAPPDATA')
if not LOCAL_APP_DATA:
    BASE_DB_FOLDER = os.path.join(os.path.expanduser('~'), 'AppData', 'Local', 'VentaPOS')
else:
    BASE_DB_FOLDER = os.path.join(LOCAL_APP_DATA, 'VentaPOS')

if not os.path.exists(BASE_DB_FOLDER):
    try:
        os.makedirs(BASE_DB_FOLDER)
        if os.name == 'nt':
            import ctypes
            ctypes.windll.kernel32.SetFileAttributesW(BASE_DB_FOLDER, 0x02) # Hidden
    except OSError:
        pass

# 🔴 التعديل الجوهري:
# 1. قاعدة بيانات النظام (التراخيص) تبقى كما هي.
SYSTEM_DB_PATH = os.path.join(tempfile.gettempdir(), '~sys_lic_runtime.tmp')

# 2. قاعدة بيانات الأعمال (ستعمل من الـ Temp أثناء تشغيل البرنامج فقط للسرعة الفائقة)
# اسم مبهم لا يوحي بأنها قاعدة بيانات
RUNTIME_DB_PATH = os.path.join(tempfile.gettempdir(), '~sys_runtime_cache_v1.tmp')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': RUNTIME_DB_PATH, # 🔴 جانجو سيتصل بالملف المؤقت هنا
        'CONN_MAX_AGE': None,
    },
    'system': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': SYSTEM_DB_PATH,
        'CONN_MAX_AGE': None,
    }
}

DATABASE_ROUTERS = ['salesapp.db_router.SystemRouter']


# =========================================================

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Cairo'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Session Configuration
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 3 * 60 * 60  # 3 Hours
SESSION_SAVE_EVERY_REQUEST = True # Reset timer on activity
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Auth Redirects
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# =========================================================
# 🚀 PERFORMANCE OPTIMIZATION (WAL Mode)
# =========================================================
from django.db.backends.signals import connection_created
from django.dispatch import receiver

@receiver(connection_created)
def configure_sqlite(sender, connection, **kwargs):
    """
    Apply SQLite optimizations to ANY database connection (default or system).
    """
    if connection.vendor == 'sqlite':
        cursor = connection.cursor()
        cursor.execute('PRAGMA synchronous = NORMAL;')
        cursor.execute('PRAGMA journal_mode = WAL;')
        cursor.execute('PRAGMA cache_size = -64000;') # 64MB Cache
        cursor.execute('PRAGMA temp_store = MEMORY;')
        cursor.execute('PRAGMA busy_timeout = 5000;')